homeshick-report: don't send emails
Leave it for the calling code to send an email.  Maybe I want to do
something other than create an email!

diff --git a/home/.local/bin/homeshick-report b/home/.local/bin/homeshick-report
--- a/home/.local/bin/homeshick-report
+++ b/home/.local/bin/homeshick-report
@@ -3,31 +3,28 @@ set -eu
 
 cd "${HOMESHICK_DIR:-$HOME/.homesick/repos}"
 
-{
-	printf 'Subject: Homeshick report from %s\n\n' "$(hostname)"
-	if [[ -x homeshick/bin/homeshick ]]; then
-		for repo in *; do
-			status=0
-			homeshick/bin/homeshick check -q "$repo" || status=$?
-			case "$status" in
-			0)
-				printf '%s: up-to-date\n' "$repo"
-				;;
-			85)  # Ahead
-				printf '%s: ahead\n' "$repo"
-				;;
-			86)  # Behind
-				printf '%s: behind\n' "$repo"
-				;;
-			88)  # Modified
-				printf '%s: modified\n' "$repo"
-				;;
-			*)
-				printf '%s: unexpected status\n' "$repo"
-				;;
-			esac
-		done
-	else
-		printf 'Could not find homesick executable in %s\n' "$(pwd)"
-	fi
-} | exim4 -bm -i -F "$USER@$HOSTNAME" -odf "$USER"
+if [[ -x homeshick/bin/homeshick ]]; then
+	for repo in *; do
+		status=0
+		homeshick/bin/homeshick check -q "$repo" || status=$?
+		case "$status" in
+		0)
+			printf '%s: up-to-date\n' "$repo"
+			;;
+		85)  # Ahead
+			printf '%s: ahead\n' "$repo"
+			;;
+		86)  # Behind
+			printf '%s: behind\n' "$repo"
+			;;
+		88)  # Modified
+			printf '%s: modified\n' "$repo"
+			;;
+		*)
+			printf '%s: unexpected status\n' "$repo"
+			;;
+		esac
+	done
+else
+	printf 'Could not find homesick executable in %s\n' "$(pwd)"
+fi
