Move toil out of this repo
It's a standalone tool, so I've packaged it as a standalone tool.

diff --git a/home/.local/bin/taskloop b/home/.local/bin/taskloop
--- a/home/.local/bin/taskloop
+++ b/home/.local/bin/taskloop
@@ -40,19 +40,10 @@ export PS4='+$EPOCHREALTIME \t $BASH_SOURCE:${FUNCNAME:-}:$LINENO: '
 # steps that aren't wanted there.
 declare -x TASKLOOP=Yes
 
-make_toil () {
-	echo 'Rebuilding toil...' >&2
-	~/.local/src/toil/install.sh
-	echo 'Done' >&2
-}
-
-if toil_path="$(command -v toil)"; then
-	if [[ ~/.local/src/toil/toil.c -nt "$toil_path"
-		|| ~/.local/src/toil/install.sh -nt "$toil_path" ]]; then
-			make_toil
-	fi
-else
-	make_toil
+if ! command -v toil >/dev/null; then
+	echo 'toil missing' >&2
+	echo 'Get it from https://github.com/me-and/toil' >&2
+	exit 69 # EX_UNAVAILABLE
 fi
 
 filter=()
