taskloop: run a bash shell for commands

diff --git a/home/.local/bin/taskloop b/home/.local/bin/taskloop
--- a/home/.local/bin/taskloop
+++ b/home/.local/bin/taskloop
@@ -10,17 +10,6 @@ else
 	filter=("${@:2}")
 fi
 
-# https://stackoverflow.com/a/31485948/220155
-shlex_file_to_array () {
-	local -n array="$1"
-	local file="$2"
-	local arg
-	array=()
-	while IFS= read -r -d '' arg; do
-		array+=("$arg")
-	done < <(xargs printf '%s\0' <"$file")
-}
-
 make_toil () {
 	echo 'Rebuilding toil...' >&2
 	~/.local/src/toil/install.sh
@@ -28,8 +17,9 @@ make_toil () {
 }
 
 if toil_path="$(command -v toil)"; then
-	if [[ ~/.local/src/toil/toil.c -nt "$toil_path" || ~/.local/src/toil/install.sh -nt "$toil_path" ]]; then
-		make_toil
+	if [[ ~/.local/src/toil/toil.c -nt "$toil_path"
+		|| ~/.local/src/toil/install.sh -nt "$toil_path" ]]; then
+			make_toil
 	fi
 else
 	make_toil
@@ -37,33 +27,31 @@ fi
 
 umask 0077
 
-toilpid=
-sleeppid=
-readpid=
+toil_pid=
+sleep_pid=
+bash_pid=
 
-flagdir="$(mktemp -dt "taskloop.$report.$$.XXXXX")"
+tmpdir="$(mktemp -dt "taskloop.$report.$$.XXXXX")"
 
 cleanup () {
-	trap - SIGWINCH
-	rm -rf "$flagdir"
+	rm -rf "$tmpdir"
 	local -a kill=()
-	[[ "$toilpid" ]] && kill+=("$toilpid")
-	[[ "$sleeppid" ]] && kill+=("$sleeppid")
-	[[ "$readpid" ]] && kill+=("$readpid")
+	[[ "$toil_pid" ]] && kill+=("$toil_pid")
+	[[ "$sleep_pid" ]] && kill+=("$sleep_pid")
+	[[ "$bash_pid" ]] && kill+=("$bash_pid")
 	if (( "${#kill[*]}" > 0 )); then
 		# kill is allowed to return non-zero because it's fairly likely
-		# one or both sleep commands will have exited already.
+		# some commands will have exited already.
 		kill "${kill[@]}" 2>/dev/null || :
 		wait "${kill[@]}"
 	fi
 }
 trap cleanup EXIT
 
-trap : SIGWINCH
-
-configfile="$flagdir"/config
-filterfile="$flagdir"/filter
-cmdfile="$flagdir"/cmd
+task_config_file="$tmpdir"/config
+task_filter_file="$tmpdir"/filter
+bash_in_use_flag_file="$tmpdir"/doingthings
+explicit_exit_flag_file="$tmpdir"/explicitexit
 
 data_path="$(task _get rc.data.location)"
 data_path="${data_path%/}"
@@ -81,77 +69,114 @@ else
 	exit 66  # EX_NOINPUT
 fi
 
-immediate_update_files=("$configfile" "$filterfile" "$config_path")
+immediate_update_files=("$task_config_file" "$task_filter_file" "$config_path")
 delay_update_files=("$data_path"/{completed,pending}.data)
 
-printf '%s\n' reserved.lines=0 verbose=blank,header,footnote,label,affected,context gc=0 >"$configfile"
-printf '%s\n' "${filter[@]}" >"$filterfile"
+have_limit=
+for f in "${filter[@]}"; do
+	if [[ "$f" = limit:* ]]; then
+		have_limit=Yes
+	fi
+done
+if [[ -z "$have_limit" ]]; then
+	filter+=(limit:page)
+fi
+printf '%s\n' "${filter[@]}" >"$task_filter_file"
+
+printf '%s\n' \
+	reserved.lines=0 \
+	verbose=blank,header,footnote,label,affected,context \
+	gc=0 \
+	>"$task_config_file"
 
 while :; do
-	if [[ -z "$readpid" ]] || ! kill -0 "$readpid" 2>/dev/null; then
-		{
-			read -r lcmd
-			printf '%s\n' "$lcmd"
-		} </dev/stdin >"$cmdfile" &
-		readpid="$!"
+	# If toil isn't already running, start it to monitor for changes to
+	# files that should trigger the task list to be redrawn if they change.
+	if [[ -z "$toil_pid" ]] || ! kill -0 "$toil_pid" 2>/dev/null; then
+		# Technically a window condition here: if files are edited
+		# between here and when toil finishes reading the state of the
+		# files as it starts up, those changes won't trigger a refresh.
+		toil "${immediate_update_files[@]}" \
+			"${delay_update_files[@]}" &
+		toil_pid="$!"
 	fi
-	if [[ -z "$toilpid" ]] || ! kill -0 "$toilpid" 2>/dev/null; then
-		toil "${immediate_update_files[@]}" "${delay_update_files[@]}" &
-		toilpid="$!"
-	fi
-	if [[ "$sleeppid" ]]; then
-		# Always restart the refresh timer when redrawing the table.
-		kill "$sleeppid" 2>/dev/null || :
+
+	# Kill any running timer and restart it, as we want to redraw the table
+	# intermittently regardless of whether there were any detected changes
+	# in order to update things like due date intervals.
+	if [[ "$sleep_pid" ]]; then
+		kill "$sleep_pid" 2>/dev/null || :
 	fi
 	sleep 15m &
-	sleeppid="$!"
-	mapfile -t config <"$configfile"
-	mapfile -t filter <"$filterfile"
-	task "${config[@]/#/rc.}" "${filter[@]}" limit:page "$report"
-	printf '%(%A %d %B %T %Z)T ' -1
-	if wait -np waitedpid "$toilpid" "$sleeppid" "$readpid"; then
+	sleep_pid="$!"
+
+	# Draw the task list.
+	mapfile -t config <"$task_config_file"
+	mapfile -t filter <"$task_filter_file"
+	task "${config[@]/#/rc.}" "${filter[@]}" "$report"
+
+	# Start an interactive Bash shell so the user can enter task commands.
+	bash_in_use_flag_file="$bash_in_use_flag_file" \
+		explicit_exit_flag_file="$explicit_exit_flag_file" \
+		tmpdir="$tmpdir" \
+		bash --rcfile ~/.local/lib/taskloop/tasklooprc -i </dev/stdin &
+	bash_pid="$!"
+
+	# Wait for one of the three background processes to exit.
+	if wait -np waited_pid "$toil_pid" "$sleep_pid" "$bash_pid"; then
 		# One of the processes returned success.
-		case "$waitedpid" in
-			"$toilpid")
+		case "$waited_pid" in
+			"$toil_pid")
 				# A file change was detected.
-				toilpid=
+				toil_pid=
 				;;
-			"$sleeppid")
+			"$sleep_pid")
 				# The timeout for doing a refresh has expired.
-				sleeppid=
+				sleep_pid=
 				;;
-			"$readpid")
-				# The user has typed a command.
-				readpid=
-				shlex_file_to_array cmd "$cmdfile"
-				if [[ -z "${cmd[*]}" ]]; then
-					# No command specified, so just
-					# refresh.
-					:
-				elif [[ "${cmd[0]}" = task ]]; then
-					# First argument of the command is
-					# "task", so just run the command.
-					"${cmd[@]}"
+			"$bash_pid")
+				# Bash has exited, either because the user
+				# successfully ran a command, or because Bash
+				# timed out.  Assume the former and loop unless
+				# the exit flag file exists.
+				if [[ -e "$explicit_exit_flag_file" ]]; then
+					# User explicitly ran the "exit"
+					# command.
+					exit 0
 				else
-					task "${cmd[@]}"
+					bash_pid=
 				fi
+				;;
+			*)
+				printf '%s:%s unexpected PID %s\n' \
+					"$0" "$LINENO" \
+					"$waited_pid" \
+					>&2
+				exit 70  # EX_SOFTWARE
 				;;
 		esac
 	else
-		waitrc="$?"
-		if (( waitrc == 156 )) && [[ ! -v waitedpid ]]; then
-			# wait ended with SIGWINCH, i.e. the terminal window
-			# size changed.  That means we need to re-run the
-			# command to fit the new terminal size.
-			:
-		else
-			# Non-zero return code or unexpected signal, so exit
-			# with that return code.
-			exit "$waitrc"
-		fi
+		# Non-zero return code or unexpected signal, so exit with that
+		# return code.
+		exit "$?"
 	fi
 
-	echo -n Updating...
+	if [[ "$bash_pid" ]] && kill -0 "$bash_pid"; then
+		# The interactive bash session is still running, so we need to
+		# terminate it if the user doesn't appear to be using it, or
+		# wait for it to be done if the user is using it.
+		if [[ ! -e "$bash_in_use_flag_file" ]]; then
+			# User doesn't appear to be using Bash, so send it a
+			# term signal if it's still running.
+			kill "$bash_pid" || :
+		fi
+
+		# Wait for the Bash process to exit.
+		wait "$bash_pid" || :
+	fi
+
+	# Wait for files that might get multiple updates in rapid succession to
+	# be stable for a couple of seconds, to avoid rapid cycling.
 	mtimewait 2 "${delay_update_files[@]}"
 done
 
